apiVersion: apps/v1
kind: Deployment
metadata:
  name: moto-api
  labels:
    app: moto-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moto-api
  template:
    metadata:
      labels:
        app: moto-api
    spec:
      containers:
        - name: moto-api
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_HOST
              value: 127.0.0.1
